[build]
  command = "npm run build"
  functions = "api"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/pt-BR/:splat"
  status = 302
  conditions = {Country = ["br", "pt", "mz", "ao", "gw", "tl", "gq", "mo", "cv", "st"]}

[[redirects]]
  from = "/*"
  to = "/en-US/:splat"
  status = 302