[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/pt-BR/:splat"
  status = 200
  force = true
  conditions = {language = ["pt", "pt-BR"]}

[[redirects]]
  from = "/*"
  to = "/en-US/:splat"
  status = 200
  force = true