[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/br/*"
  conditions = {language = ["pt", "pt-BR"]}
  force = true

[[redirects]]
  from = "/*"
  to = "/en/*"
  force = true