[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/br/:splat"
  status = 302
  conditions = {language = ["pt", "pt-BR"]}

[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302